alf007_topiccalendar_controller:
    path: /topiccalendar/{month}/{year}
    methods: [GET]
    defaults: { _controller: alf007.topiccalendar.controller:handle, month: 0, year: 0 }
    requirements:
        month: \d+
        year: \d+
alf007_topiccalendar_controller_minical:
    path: /minicalendar/{month}/{year}
    methods: [GET]
    defaults: { _controller: alf007.topiccalendar.controller:display_mini_calendar, month: 0, year: 0 }
    requirements:
        month: \d+
        year: \d+
